const letterDuration = 200

export default {
	file: "data.wav",
	triggers: [
		{ key_name: "KEY_1", value: "gwah", shift: true, fadeout: 100 },
		{ key_name: "KEY_A", value: "a", fadeout: 100 },
		{ key_name: "KEY_B", value: "b", fadeout: 100 },
		{ key_name: "KEY_C", value: "c", fadeout: 100 },
		{ key_name: "KEY_D", value: "d", fadeout: 100 },
		{ key_name: "KEY_E", value: "e", fadeout: 100 },
		{ key_name: "KEY_F", value: "f", fadeout: 100 },
		{ key_name: "KEY_G", value: "g", fadeout: 100 },
		{ key_name: "KEY_H", value: "h", fadeout: 100 },
		{ key_name: "KEY_I", value: "i", fadeout: 100 },
		{ key_name: "KEY_J", value: "j", fadeout: 100 },
		{ key_name: "KEY_K", value: "k", fadeout: 100 },
		{ key_name: "KEY_L", value: "l", fadeout: 100 },
		{ key_name: "KEY_M", value: "m", fadeout: 100 },
		{ key_name: "KEY_N", value: "n", fadeout: 100 },
		{ key_name: "KEY_O", value: "o", fadeout: 100 },
		{ key_name: "KEY_P", value: "p", fadeout: 100 },
		{ key_name: "KEY_Q", value: "q", fadeout: 100 },
		{ key_name: "KEY_R", value: "r", fadeout: 100 },
		{ key_name: "KEY_S", value: "s", fadeout: 100 },
		{ key_name: "KEY_T", value: "t", fadeout: 100 },
		{ key_name: "KEY_U", value: "u", fadeout: 100 },
		{ key_name: "KEY_V", value: "v", fadeout: 100 },
		{ key_name: "KEY_W", value: "w", fadeout: 100 },
		{ key_name: "KEY_X", value: "x", fadeout: 100 },
		{ key_name: "KEY_Y", value: "y", fadeout: 100 },
		{ key_name: "KEY_Z", value: "z", fadeout: 100 },
	],
	keys: {
		a: [0, letterDuration],
		b: [letterDuration * 1, letterDuration],
		c: [letterDuration * 2, letterDuration],
		d: [letterDuration * 3, letterDuration],
		e: [letterDuration * 4, letterDuration],
		f: [letterDuration * 5, letterDuration],
		g: [letterDuration * 6, letterDuration],
		h: [letterDuration * 7, letterDuration],
		i: [letterDuration * 8, letterDuration],
		j: [letterDuration * 9, letterDuration],
		k: [letterDuration * 10, letterDuration],
		l: [letterDuration * 11, letterDuration],
		m: [letterDuration * 12, letterDuration],
		n: [letterDuration * 13, letterDuration],
		o: [letterDuration * 14, letterDuration],
		p: [letterDuration * 15, letterDuration],
		q: [letterDuration * 16, letterDuration],
		r: [letterDuration * 17, letterDuration],
		s: [letterDuration * 18, letterDuration],
		t: [letterDuration * 19, letterDuration],
		u: [letterDuration * 20, letterDuration],
		v: [letterDuration * 21, letterDuration],
		w: [letterDuration * 22, letterDuration],
		x: [letterDuration * 23, letterDuration],
		y: [letterDuration * 24, letterDuration],
		z: [letterDuration * 25, letterDuration],
		ok: [600 * 0 + 200 * 26, 600],
		gwah: [600 * 1 + 200 * 26, 600],
		deska: [600 * 2 + 200 * 26, 600],
	},
}
